version: "3.8"

services:
  smtp-oauth-relay:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.docker
    container_name: smtp-relay
    hostname: smtp-oauth-relay.local
    restart: unless-stopped
    ports:
      - "2625:8025"  # Expose SMTP on port 8025
    networks:
      - smtp

networks:
  smtp:
    name: smtp
